@url = http://localhost:3000/tags

### Post
POST {{url}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJpbHlhcy5iaWthcm5hZjFAZ21haWwuY29tIiwiaWF0IjoxNzY1ODk4NzUzLCJleHAiOjE3NjU5MDIzNTMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.fXMIExihhAM2cflz418QSuOGZx71t0YxOZAcG0JjvOQ

{
  "name": "typescript",
  "slug": "typescript",
  "description": "all posts are typescript"
}

###Delete tag
DELETE {{url}}?id=3


### Get tag
GET {{url}}