@url=http://localhost:3000/users


### Get Users
GET {{url}}/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJpbHlhcy5iaWthcm5hZjFAZ21haWwuY29tIiwiaWF0IjoxNzY2MTY0NDU4LCJleHAiOjE3NjYxNjgwNTgsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Tqbn82BMt_1GmZtNZlctzAP9sR2pE6pIwUoIDVIyepQ



### create user
POST {{url}}
Content-Type: application/json

{
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "ilyas.bikarnaf4@gmail.com",
  "password": "Password123#"
}


### create users
POST {{url}}/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiZW1haWwiOiJpbHlhcy5iaWthcm5hZjFAZ21haWwuY29tIiwiaWF0IjoxNzY1NzE4OTU3LCJleHAiOjE3NjU3MjI1NTcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.1hdUD4kSTXmnBcA3898FBiOjHMGN87wDuKHfAdadr5I

{
  "users": [{
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "alksjdf2aslkdfj@alskdjf.com",
  "password": "Password123#"
}, {
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "alksjdlkdfj@alskdjf.com",
  "password": "Password123#"
}]
}




### Patch Request
PATCH {{url}}
Content-Type: application/json
{
  "firstName": "test",
  "lastName": "test",
  "email": "haha@alsjdf.fff",
}