@url=http://localhost:3000/users


### Get Users
GET {{url}}/

### create user
POST {{url}}
Content-Type: application/json

{
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "ilyas.bikarnaf1@gmail.com",
  "password": "Password123#"
}


### create users
POST {{url}}/create-many
Content-Type: application/json

{
  "users": [{
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "alksjdf2aslkdfj@alskdjf.com",
  "password": "Password123#"
}, {
  "firstName": "Ilyas",
  "lastName": "Bikarnaf",
  "email": "alksjdlkdfj@alskdjf.com",
  "password": "Password123#"
}]
}




### Patch Request
PATCH {{url}}
Content-Type: application/json
{
  "firstName": "test",
  "lastName": "test",
  "email": "haha@alsjdf.fff",
}