POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "email": "ilyas.bikarnaf1@gmail.com", 
  "password": "Password123#"
}


### refresh token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaWF0IjoxNzY1OTgwMzYwLCJleHAiOjE3NjYwNjY3NjAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.0tyRUoSaWj9J3h5lDRuGbNMN1WXKXIZtZiZ0aclFkLI"
}

